server:
  port: 9000

spring:
  application:
    name: main
  datasource:
    url: jdbc:mysql://localhost:3306/bbang0
    username: root
    password: dnjsehddus99@mysql
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8??

jpa:
  hibernate:
    ddl-auto: none